// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnun96eTpun21wFHwhztuB1Oxc6wu-_18',
    appId: '1:730432343549:web:cd60a81aebd0237b03dd94',
    messagingSenderId: '730432343549',
    projectId: 'logintest-iso',
    authDomain: 'logintest-iso.firebaseapp.com',
    storageBucket: 'logintest-iso.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuWPBzpmaUhGDvnQfjiku89lzZx4rYI8',
    appId: '1:730432343549:android:d7d9435a80816dcf03dd94',
    messagingSenderId: '730432343549',
    projectId: 'logintest-iso',
    storageBucket: 'logintest-iso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkMKnpAYN8n9UZtEz8x4PJwIfNUXYrL_Q',
    appId: '1:730432343549:ios:aa84f28dce26698a03dd94',
    messagingSenderId: '730432343549',
    projectId: 'logintest-iso',
    storageBucket: 'logintest-iso.appspot.com',
    iosClientId:
        '730432343549-tmfbrsi49r8gddnhq94vj3bloknqdstb.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkMKnpAYN8n9UZtEz8x4PJwIfNUXYrL_Q',
    appId: '1:730432343549:ios:7c16d16d453a156c03dd94',
    messagingSenderId: '730432343549',
    projectId: 'logintest-iso',
    storageBucket: 'logintest-iso.appspot.com',
    iosClientId:
        '730432343549-7h0cnvbbctun6fpmj3ah2se62ldv3i7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaselearn.RunnerTests',
  );
}
